import Foundation
import SwiftData

enum ActionKind: String, Codable, CaseIterable, Sendable {
    case task   // one-off todo → exports to Reminders
    case event  // time-boxed practice → exports to Calendar

    var displayName: String {
        switch self {
        case .task:  return "To-do"
        case .event: return "Scheduled"
        }
    }
}

/// One step of a book's implementation plan ("Act" tab). Plans arrive
/// pre-curated with summary packs or are generated by `ActionPlanEngine`.
/// Items can be checked off in-app and exported to the system Calendar
/// (events) or Reminders (tasks) via `PlannerService`.
@Model
final class ActionItem {
    var id: UUID = UUID()
    var book: Book?
    var title: String = ""
    var detail: String = ""
    var kindRaw: String = ActionKind.task.rawValue
    /// Day of the plan this item belongs to (1-based).
    var dayOffset: Int = 1
    /// Suggested duration for `.event` items; 0 for plain tasks.
    var durationMinutes: Int = 0
    /// Position within the plan (stable sort across equal days).
    var order: Int = 0
    var completed: Bool = false
    var completedAt: Date?
    /// Set when the item was exported to Calendar / Reminders.
    var scheduledAt: Date?
    var exportedToSystem: Bool = false
    var createdAt: Date = Date.now

    init(
        id: UUID = UUID(),
        book: Book? = nil,
        title: String,
        detail: String = "",
        kind: ActionKind = .task,
        dayOffset: Int = 1,
        durationMinutes: Int = 0,
        order: Int = 0
    ) {
        self.id = id
        self.book = book
        self.title = title
        self.detail = detail
        self.kindRaw = kind.rawValue
        self.dayOffset = dayOffset
        self.durationMinutes = durationMinutes
        self.order = order
        self.createdAt = .now
    }

    var kind: ActionKind {
        get { ActionKind(rawValue: kindRaw) ?? .task }
        set { kindRaw = newValue.rawValue }
    }
}
